/********************************************************************************
** Form generated from reading UI file 'mainwin.ui'
**
** Created by: Qt User Interface Compiler version 5.15.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWIN_H
#define UI_MAINWIN_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateTimeEdit>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWin
{
public:
    QAction *action_Help;
    QAction *action_About;
    QAction *mnDisplayPocsag;
    QAction *mnSendSinglePage;
    QWidget *centralwidget;
    QGridLayout *gridLayout;
    QTabWidget *twMain;
    QWidget *tabPageEnter;
    QTextEdit *teMessage;
    QLabel *label;
    QLabel *label_4;
    QLineEdit *leRic;
    QPushButton *pbSend;
    QListWidget *lwPrevPages;
    QGroupBox *gbFunctionBits;
    QToolButton *tbFuncNumeric;
    QToolButton *tbFuncTone1;
    QToolButton *tbFuncTone2;
    QToolButton *tbFuncAlpha;
    QGroupBox *gbBaudRate;
    QToolButton *tb512;
    QToolButton *tb2400;
    QToolButton *tb1200;
    QGroupBox *gbAlphaNumeric;
    QToolButton *tbAlpha;
    QToolButton *tbNumeric;
    QGroupBox *gbDataState;
    QToolButton *tbNormal;
    QToolButton *tbInverted;
    QGroupBox *gbTuneup;
    QToolButton *tbTune;
    QToolButton *tbTuneStop;
    QGroupBox *gbLevel;
    QSlider *pocsagLevel;
    QLabel *label_3;
    QLabel *levelLabel;
    QLabel *label_9;
    QFrame *line;
    QFrame *line_2;
    QLabel *verLabel;
    QGroupBox *groupBox;
    QSpinBox *sbPeriodQty;
    QComboBox *cbPeriod;
    QSpinBox *sbHowMany;
    QGroupBox *groupBox_2;
    QDateTimeEdit *dtSendTime;
    QToolButton *tbResetTime;
    QGroupBox *groupBox_3;
    QSpinBox *sbTx;
    QGroupBox *groupBox_4;
    QLineEdit *lePagerName;
    QToolButton *tbGetPagerID;
    QWidget *tabRicSearch;
    QListWidget *lwRicSearch;
    QLineEdit *leStartRic;
    QLabel *label_10;
    QLabel *searchInfo;
    QPushButton *pbStart;
    QLabel *label_12;
    QSpinBox *sbAmtRics;
    QSpinBox *sbAmtTxs;
    QCheckBox *cbSendRic;
    QPushButton *pbAbort;
    QWidget *tabPocsagData;
    QGridLayout *gridLayout_2;
    QListWidget *lwPocsag;
    QWidget *tabLogFile;
    QPlainTextEdit *logFile;
    QPushButton *pbSave;
    QPushButton *pbReload;
    QWidget *tabPagerIDs;
    QGroupBox *gbCustomers;
    QGroupBox *groupBox_5;
    QSpinBox *sbTx_2;
    QLineEdit *leRic_2;
    QGroupBox *gbAlphaNumeric_2;
    QToolButton *tbAlpha_2;
    QToolButton *tbNumeric_2;
    QLabel *label_13;
    QGroupBox *gbFunctionBits_2;
    QToolButton *tbFuncNumeric_2;
    QToolButton *tbFuncTone1_2;
    QToolButton *tbFuncTone2_2;
    QToolButton *tbFuncAlpha_2;
    QGroupBox *gbBaudRate_2;
    QToolButton *tb512_2;
    QToolButton *tb2400_2;
    QToolButton *tb1200_2;
    QLabel *label_11;
    QLineEdit *leName_2;
    QPushButton *pbUpdateEntry;
    QPushButton *pbDeleteEntry;
    QLabel *label_18;
    QLineEdit *leFrequency;
    QPushButton *pbAddEntry;
    QSpinBox *sbMaxMsgLen;
    QLabel *label_20;
    QPushButton *pbClearAll;
    QListWidget *lwPagerIDs;
    QLabel *label_19;
    QWidget *tabPagerMsgs;
    QGroupBox *gbPagerMessages;
    QGroupBox *gbAlphaNumeric_3;
    QToolButton *tbAlpha_3;
    QToolButton *tbNumeric_3;
    QGroupBox *gbFunctionBits_3;
    QToolButton *tbFuncNumeric_3;
    QToolButton *tbFuncTone1_3;
    QToolButton *tbFuncTone2_3;
    QToolButton *tbFuncAlpha_3;
    QTextEdit *teMessage_3;
    QLabel *label_15;
    QLabel *label_16;
    QGroupBox *gbBaudRate_3;
    QToolButton *tb512_3;
    QToolButton *tb2400_3;
    QToolButton *tb1200_3;
    QGroupBox *groupBox_8;
    QSpinBox *sbTx_3;
    QLineEdit *leRic_3;
    QGroupBox *groupBox_9;
    QDateTimeEdit *dtSendTime_3;
    QGroupBox *groupBox_11;
    QComboBox *cbFlags_3;
    QPushButton *pbDeleteEntry_3;
    QGroupBox *groupBox_10;
    QSpinBox *sbPeriodQty_3;
    QComboBox *cbPeriod_3;
    QSpinBox *sbHowMany_3;
    QListWidget *lwPages;
    QLabel *pagerMsgsHeader;
    QWidget *tabSetup;
    QPushButton *pbApply;
    QGroupBox *groupBox_6;
    QLabel *label_22;
    QLineEdit *leBaudOrder;
    QGroupBox *groupBox_7;
    QLineEdit *leTxOrder;
    QLabel *label_21;
    QGroupBox *groupBox_12;
    QLineEdit *leNormInv;
    QLabel *label_14;
    QPushButton *pbKeyTx;
    QSpinBox *sbTxTest;
    QGroupBox *groupBox_13;
    QLineEdit *leKeyDelay;
    QLabel *label_17;
    QGroupBox *groupBox_14;
    QLineEdit *leSyncCW;
    QLineEdit *leIdleCW;
    QLabel *label_2;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QGroupBox *groupBox_15;
    QRadioButton *rbPic;
    QRadioButton *rbSop;
    QGroupBox *groupBox_16;
    QComboBox *mixer_device;

    void setupUi(QMainWindow *MainWin)
    {
        if (MainWin->objectName().isEmpty())
            MainWin->setObjectName(QString::fromUtf8("MainWin"));
        MainWin->resize(650, 480);
        MainWin->setMinimumSize(QSize(650, 480));
        MainWin->setMaximumSize(QSize(650, 480));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/images/gascop.png"), QSize(), QIcon::Normal, QIcon::Off);
        MainWin->setWindowIcon(icon);
        action_Help = new QAction(MainWin);
        action_Help->setObjectName(QString::fromUtf8("action_Help"));
        action_About = new QAction(MainWin);
        action_About->setObjectName(QString::fromUtf8("action_About"));
        mnDisplayPocsag = new QAction(MainWin);
        mnDisplayPocsag->setObjectName(QString::fromUtf8("mnDisplayPocsag"));
        mnSendSinglePage = new QAction(MainWin);
        mnSendSinglePage->setObjectName(QString::fromUtf8("mnSendSinglePage"));
        centralwidget = new QWidget(MainWin);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        gridLayout = new QGridLayout(centralwidget);
        gridLayout->setSpacing(2);
        gridLayout->setContentsMargins(2, 2, 2, 2);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        twMain = new QTabWidget(centralwidget);
        twMain->setObjectName(QString::fromUtf8("twMain"));
        twMain->setEnabled(true);
        twMain->setMaximumSize(QSize(16777215, 5000));
        QFont font;
        font.setPointSize(10);
        twMain->setFont(font);
        twMain->setDocumentMode(true);
        tabPageEnter = new QWidget();
        tabPageEnter->setObjectName(QString::fromUtf8("tabPageEnter"));
        teMessage = new QTextEdit(tabPageEnter);
        teMessage->setObjectName(QString::fromUtf8("teMessage"));
        teMessage->setGeometry(QRect(120, 186, 523, 67));
        teMessage->setTabChangesFocus(true);
        label = new QLabel(tabPageEnter);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(4, 164, 93, 16));
        label_4 = new QLabel(tabPageEnter);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(4, 186, 69, 16));
        leRic = new QLineEdit(tabPageEnter);
        leRic->setObjectName(QString::fromUtf8("leRic"));
        leRic->setGeometry(QRect(120, 160, 93, 24));
        leRic->setMaxLength(7);
        pbSend = new QPushButton(tabPageEnter);
        pbSend->setObjectName(QString::fromUtf8("pbSend"));
        pbSend->setGeometry(QRect(26, 220, 61, 25));
        lwPrevPages = new QListWidget(tabPageEnter);
        lwPrevPages->setObjectName(QString::fromUtf8("lwPrevPages"));
        lwPrevPages->setGeometry(QRect(120, 260, 523, 159));
        gbFunctionBits = new QGroupBox(tabPageEnter);
        gbFunctionBits->setObjectName(QString::fromUtf8("gbFunctionBits"));
        gbFunctionBits->setGeometry(QRect(4, 4, 183, 45));
        gbFunctionBits->setCheckable(false);
        tbFuncNumeric = new QToolButton(gbFunctionBits);
        tbFuncNumeric->setObjectName(QString::fromUtf8("tbFuncNumeric"));
        tbFuncNumeric->setGeometry(QRect(4, 14, 42, 26));
        QFont font1;
        font1.setPointSize(9);
        tbFuncNumeric->setFont(font1);
        tbFuncNumeric->setIconSize(QSize(23, 23));
        tbFuncNumeric->setCheckable(true);
        tbFuncNumeric->setChecked(false);
        tbFuncNumeric->setAutoExclusive(true);
        tbFuncTone1 = new QToolButton(gbFunctionBits);
        tbFuncTone1->setObjectName(QString::fromUtf8("tbFuncTone1"));
        tbFuncTone1->setGeometry(QRect(48, 14, 42, 26));
        tbFuncTone1->setFont(font1);
        tbFuncTone1->setCheckable(true);
        tbFuncTone1->setChecked(false);
        tbFuncTone1->setAutoExclusive(true);
        tbFuncTone2 = new QToolButton(gbFunctionBits);
        tbFuncTone2->setObjectName(QString::fromUtf8("tbFuncTone2"));
        tbFuncTone2->setGeometry(QRect(92, 14, 42, 26));
        tbFuncTone2->setFont(font1);
        tbFuncTone2->setCheckable(true);
        tbFuncTone2->setChecked(false);
        tbFuncTone2->setAutoExclusive(true);
        tbFuncAlpha = new QToolButton(gbFunctionBits);
        tbFuncAlpha->setObjectName(QString::fromUtf8("tbFuncAlpha"));
        tbFuncAlpha->setGeometry(QRect(136, 14, 42, 26));
        tbFuncAlpha->setFont(font1);
        tbFuncAlpha->setCheckable(true);
        tbFuncAlpha->setChecked(true);
        tbFuncAlpha->setAutoExclusive(true);
        gbBaudRate = new QGroupBox(tabPageEnter);
        gbBaudRate->setObjectName(QString::fromUtf8("gbBaudRate"));
        gbBaudRate->setGeometry(QRect(362, 4, 137, 45));
        tb512 = new QToolButton(gbBaudRate);
        tb512->setObjectName(QString::fromUtf8("tb512"));
        tb512->setGeometry(QRect(4, 14, 42, 26));
        tb512->setCheckable(true);
        tb512->setAutoExclusive(true);
        tb2400 = new QToolButton(gbBaudRate);
        tb2400->setObjectName(QString::fromUtf8("tb2400"));
        tb2400->setGeometry(QRect(92, 14, 42, 26));
        tb2400->setCheckable(true);
        tb2400->setAutoExclusive(true);
        tb1200 = new QToolButton(gbBaudRate);
        tb1200->setObjectName(QString::fromUtf8("tb1200"));
        tb1200->setGeometry(QRect(48, 14, 42, 26));
        tb1200->setCheckable(true);
        tb1200->setChecked(true);
        tb1200->setAutoExclusive(true);
        gbAlphaNumeric = new QGroupBox(tabPageEnter);
        gbAlphaNumeric->setObjectName(QString::fromUtf8("gbAlphaNumeric"));
        gbAlphaNumeric->setGeometry(QRect(197, 4, 155, 45));
        tbAlpha = new QToolButton(gbAlphaNumeric);
        tbAlpha->setObjectName(QString::fromUtf8("tbAlpha"));
        tbAlpha->setGeometry(QRect(6, 14, 70, 26));
        tbAlpha->setCheckable(true);
        tbAlpha->setChecked(true);
        tbAlpha->setAutoExclusive(true);
        tbNumeric = new QToolButton(gbAlphaNumeric);
        tbNumeric->setObjectName(QString::fromUtf8("tbNumeric"));
        tbNumeric->setGeometry(QRect(80, 14, 70, 26));
        tbNumeric->setCheckable(true);
        tbNumeric->setAutoExclusive(true);
        gbDataState = new QGroupBox(tabPageEnter);
        gbDataState->setObjectName(QString::fromUtf8("gbDataState"));
        gbDataState->setGeometry(QRect(510, 4, 131, 45));
        tbNormal = new QToolButton(gbDataState);
        tbNormal->setObjectName(QString::fromUtf8("tbNormal"));
        tbNormal->setGeometry(QRect(4, 14, 60, 26));
        tbNormal->setCheckable(true);
        tbNormal->setChecked(true);
        tbNormal->setAutoExclusive(true);
        tbInverted = new QToolButton(gbDataState);
        tbInverted->setObjectName(QString::fromUtf8("tbInverted"));
        tbInverted->setGeometry(QRect(66, 14, 60, 26));
        tbInverted->setCheckable(true);
        tbInverted->setAutoExclusive(true);
        gbTuneup = new QGroupBox(tabPageEnter);
        gbTuneup->setObjectName(QString::fromUtf8("gbTuneup"));
        gbTuneup->setGeometry(QRect(4, 100, 225, 47));
        tbTune = new QToolButton(gbTuneup);
        tbTune->setObjectName(QString::fromUtf8("tbTune"));
        tbTune->setGeometry(QRect(4, 16, 105, 26));
        tbTuneStop = new QToolButton(gbTuneup);
        tbTuneStop->setObjectName(QString::fromUtf8("tbTuneStop"));
        tbTuneStop->setGeometry(QRect(114, 16, 105, 26));
        gbLevel = new QGroupBox(tabPageEnter);
        gbLevel->setObjectName(QString::fromUtf8("gbLevel"));
        gbLevel->setGeometry(QRect(240, 100, 401, 47));
        pocsagLevel = new QSlider(gbLevel);
        pocsagLevel->setObjectName(QString::fromUtf8("pocsagLevel"));
        pocsagLevel->setGeometry(QRect(6, 12, 357, 20));
        pocsagLevel->setMinimum(1);
        pocsagLevel->setMaximum(128);
        pocsagLevel->setValue(64);
        pocsagLevel->setOrientation(Qt::Horizontal);
        pocsagLevel->setInvertedAppearance(false);
        pocsagLevel->setInvertedControls(true);
        pocsagLevel->setTickPosition(QSlider::NoTicks);
        pocsagLevel->setTickInterval(16);
        label_3 = new QLabel(gbLevel);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 28, 349, 16));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Monospace"));
        font2.setPointSize(8);
        font2.setBold(false);
        label_3->setFont(font2);
        levelLabel = new QLabel(gbLevel);
        levelLabel->setObjectName(QString::fromUtf8("levelLabel"));
        levelLabel->setGeometry(QRect(368, 14, 29, 16));
        label_9 = new QLabel(tabPageEnter);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(4, 262, 101, 16));
        line = new QFrame(tabPageEnter);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(-2, 248, 647, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(tabPageEnter);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(0, 146, 647, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        verLabel = new QLabel(tabPageEnter);
        verLabel->setObjectName(QString::fromUtf8("verLabel"));
        verLabel->setGeometry(QRect(2, 406, 119, 16));
        groupBox = new QGroupBox(tabPageEnter);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(176, 52, 245, 45));
        sbPeriodQty = new QSpinBox(groupBox);
        sbPeriodQty->setObjectName(QString::fromUtf8("sbPeriodQty"));
        sbPeriodQty->setGeometry(QRect(8, 16, 47, 24));
        sbPeriodQty->setMaximum(60);
        cbPeriod = new QComboBox(groupBox);
        cbPeriod->addItem(QString());
        cbPeriod->addItem(QString());
        cbPeriod->addItem(QString());
        cbPeriod->addItem(QString());
        cbPeriod->addItem(QString());
        cbPeriod->addItem(QString());
        cbPeriod->setObjectName(QString::fromUtf8("cbPeriod"));
        cbPeriod->setGeometry(QRect(60, 16, 83, 24));
        sbHowMany = new QSpinBox(groupBox);
        sbHowMany->setObjectName(QString::fromUtf8("sbHowMany"));
        sbHowMany->setGeometry(QRect(148, 16, 87, 24));
        sbHowMany->setMinimum(-1);
        sbHowMany->setValue(-1);
        groupBox_2 = new QGroupBox(tabPageEnter);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(4, 52, 167, 45));
        dtSendTime = new QDateTimeEdit(groupBox_2);
        dtSendTime->setObjectName(QString::fromUtf8("dtSendTime"));
        dtSendTime->setGeometry(QRect(4, 16, 157, 24));
        dtSendTime->setWrapping(true);
        dtSendTime->setAccelerated(true);
        dtSendTime->setCalendarPopup(false);
        tbResetTime = new QToolButton(groupBox_2);
        tbResetTime->setObjectName(QString::fromUtf8("tbResetTime"));
        tbResetTime->setGeometry(QRect(150, 8, 10, 10));
        groupBox_3 = new QGroupBox(tabPageEnter);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(426, 52, 49, 45));
        sbTx = new QSpinBox(groupBox_3);
        sbTx->setObjectName(QString::fromUtf8("sbTx"));
        sbTx->setGeometry(QRect(4, 16, 41, 24));
        sbTx->setMinimum(1);
        sbTx->setMaximum(8);
        groupBox_4 = new QGroupBox(tabPageEnter);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(482, 52, 159, 45));
        lePagerName = new QLineEdit(groupBox_4);
        lePagerName->setObjectName(QString::fromUtf8("lePagerName"));
        lePagerName->setGeometry(QRect(6, 16, 125, 24));
        tbGetPagerID = new QToolButton(groupBox_4);
        tbGetPagerID->setObjectName(QString::fromUtf8("tbGetPagerID"));
        tbGetPagerID->setGeometry(QRect(134, 16, 21, 23));
        twMain->addTab(tabPageEnter, QString());
        tabRicSearch = new QWidget();
        tabRicSearch->setObjectName(QString::fromUtf8("tabRicSearch"));
        lwRicSearch = new QListWidget(tabRicSearch);
        lwRicSearch->setObjectName(QString::fromUtf8("lwRicSearch"));
        lwRicSearch->setGeometry(QRect(2, 2, 643, 327));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Monospace"));
        font3.setPointSize(10);
        lwRicSearch->setFont(font3);
        leStartRic = new QLineEdit(tabRicSearch);
        leStartRic->setObjectName(QString::fromUtf8("leStartRic"));
        leStartRic->setGeometry(QRect(68, 366, 73, 24));
        leStartRic->setMaxLength(7);
        label_10 = new QLabel(tabRicSearch);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(6, 370, 63, 16));
        searchInfo = new QLabel(tabRicSearch);
        searchInfo->setObjectName(QString::fromUtf8("searchInfo"));
        searchInfo->setGeometry(QRect(6, 400, 331, 16));
        pbStart = new QPushButton(tabRicSearch);
        pbStart->setObjectName(QString::fromUtf8("pbStart"));
        pbStart->setGeometry(QRect(520, 394, 59, 25));
        label_12 = new QLabel(tabRicSearch);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(4, 332, 639, 31));
        label_12->setAlignment(Qt::AlignCenter);
        label_12->setWordWrap(true);
        sbAmtRics = new QSpinBox(tabRicSearch);
        sbAmtRics->setObjectName(QString::fromUtf8("sbAmtRics"));
        sbAmtRics->setGeometry(QRect(144, 366, 247, 24));
        sbAmtRics->setMinimum(256);
        sbAmtRics->setMaximum(4096);
        sbAmtRics->setSingleStep(256);
        sbAmtRics->setValue(512);
        sbAmtTxs = new QSpinBox(tabRicSearch);
        sbAmtTxs->setObjectName(QString::fromUtf8("sbAmtTxs"));
        sbAmtTxs->setGeometry(QRect(400, 366, 197, 24));
        sbAmtTxs->setAccelerated(true);
        sbAmtTxs->setMinimum(1);
        sbAmtTxs->setMaximum(4096);
        cbSendRic = new QCheckBox(tabRicSearch);
        cbSendRic->setObjectName(QString::fromUtf8("cbSendRic"));
        cbSendRic->setGeometry(QRect(358, 398, 157, 20));
        pbAbort = new QPushButton(tabRicSearch);
        pbAbort->setObjectName(QString::fromUtf8("pbAbort"));
        pbAbort->setEnabled(false);
        pbAbort->setGeometry(QRect(582, 394, 59, 25));
        twMain->addTab(tabRicSearch, QString());
        tabPocsagData = new QWidget();
        tabPocsagData->setObjectName(QString::fromUtf8("tabPocsagData"));
        gridLayout_2 = new QGridLayout(tabPocsagData);
        gridLayout_2->setSpacing(2);
        gridLayout_2->setContentsMargins(2, 2, 2, 2);
        gridLayout_2->setObjectName(QString::fromUtf8("gridLayout_2"));
        lwPocsag = new QListWidget(tabPocsagData);
        lwPocsag->setObjectName(QString::fromUtf8("lwPocsag"));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Monospace"));
        font4.setPointSize(10);
        font4.setBold(false);
        lwPocsag->setFont(font4);
        lwPocsag->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);

        gridLayout_2->addWidget(lwPocsag, 0, 0, 1, 1);

        twMain->addTab(tabPocsagData, QString());
        tabLogFile = new QWidget();
        tabLogFile->setObjectName(QString::fromUtf8("tabLogFile"));
        logFile = new QPlainTextEdit(tabLogFile);
        logFile->setObjectName(QString::fromUtf8("logFile"));
        logFile->setGeometry(QRect(0, 0, 647, 393));
        logFile->setFont(font1);
        logFile->setReadOnly(false);
        pbSave = new QPushButton(tabLogFile);
        pbSave->setObjectName(QString::fromUtf8("pbSave"));
        pbSave->setGeometry(QRect(574, 396, 70, 25));
        pbReload = new QPushButton(tabLogFile);
        pbReload->setObjectName(QString::fromUtf8("pbReload"));
        pbReload->setGeometry(QRect(500, 396, 70, 25));
        twMain->addTab(tabLogFile, QString());
        tabPagerIDs = new QWidget();
        tabPagerIDs->setObjectName(QString::fromUtf8("tabPagerIDs"));
        gbCustomers = new QGroupBox(tabPagerIDs);
        gbCustomers->setObjectName(QString::fromUtf8("gbCustomers"));
        gbCustomers->setGeometry(QRect(2, 2, 641, 135));
        groupBox_5 = new QGroupBox(gbCustomers);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(566, 18, 61, 45));
        sbTx_2 = new QSpinBox(groupBox_5);
        sbTx_2->setObjectName(QString::fromUtf8("sbTx_2"));
        sbTx_2->setGeometry(QRect(8, 16, 47, 24));
        sbTx_2->setMinimum(1);
        sbTx_2->setMaximum(8);
        leRic_2 = new QLineEdit(gbCustomers);
        leRic_2->setObjectName(QString::fromUtf8("leRic_2"));
        leRic_2->setGeometry(QRect(116, 74, 75, 24));
        leRic_2->setMaxLength(7);
        gbAlphaNumeric_2 = new QGroupBox(gbCustomers);
        gbAlphaNumeric_2->setObjectName(QString::fromUtf8("gbAlphaNumeric_2"));
        gbAlphaNumeric_2->setGeometry(QRect(222, 18, 153, 45));
        tbAlpha_2 = new QToolButton(gbAlphaNumeric_2);
        tbAlpha_2->setObjectName(QString::fromUtf8("tbAlpha_2"));
        tbAlpha_2->setGeometry(QRect(4, 14, 70, 26));
        tbAlpha_2->setCheckable(true);
        tbAlpha_2->setChecked(true);
        tbAlpha_2->setAutoExclusive(true);
        tbNumeric_2 = new QToolButton(gbAlphaNumeric_2);
        tbNumeric_2->setObjectName(QString::fromUtf8("tbNumeric_2"));
        tbNumeric_2->setGeometry(QRect(76, 14, 70, 26));
        tbNumeric_2->setCheckable(true);
        tbNumeric_2->setAutoExclusive(true);
        label_13 = new QLabel(gbCustomers);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(14, 80, 93, 16));
        gbFunctionBits_2 = new QGroupBox(gbCustomers);
        gbFunctionBits_2->setObjectName(QString::fromUtf8("gbFunctionBits_2"));
        gbFunctionBits_2->setGeometry(QRect(14, 18, 183, 45));
        gbFunctionBits_2->setCheckable(false);
        tbFuncNumeric_2 = new QToolButton(gbFunctionBits_2);
        tbFuncNumeric_2->setObjectName(QString::fromUtf8("tbFuncNumeric_2"));
        tbFuncNumeric_2->setGeometry(QRect(4, 14, 42, 26));
        tbFuncNumeric_2->setFont(font1);
        tbFuncNumeric_2->setIconSize(QSize(23, 23));
        tbFuncNumeric_2->setCheckable(true);
        tbFuncNumeric_2->setChecked(false);
        tbFuncNumeric_2->setAutoExclusive(true);
        tbFuncTone1_2 = new QToolButton(gbFunctionBits_2);
        tbFuncTone1_2->setObjectName(QString::fromUtf8("tbFuncTone1_2"));
        tbFuncTone1_2->setGeometry(QRect(48, 14, 42, 26));
        tbFuncTone1_2->setFont(font1);
        tbFuncTone1_2->setCheckable(true);
        tbFuncTone1_2->setChecked(false);
        tbFuncTone1_2->setAutoExclusive(true);
        tbFuncTone2_2 = new QToolButton(gbFunctionBits_2);
        tbFuncTone2_2->setObjectName(QString::fromUtf8("tbFuncTone2_2"));
        tbFuncTone2_2->setGeometry(QRect(92, 14, 42, 26));
        tbFuncTone2_2->setFont(font1);
        tbFuncTone2_2->setCheckable(true);
        tbFuncTone2_2->setChecked(false);
        tbFuncTone2_2->setAutoExclusive(true);
        tbFuncAlpha_2 = new QToolButton(gbFunctionBits_2);
        tbFuncAlpha_2->setObjectName(QString::fromUtf8("tbFuncAlpha_2"));
        tbFuncAlpha_2->setGeometry(QRect(136, 14, 42, 26));
        tbFuncAlpha_2->setFont(font1);
        tbFuncAlpha_2->setCheckable(true);
        tbFuncAlpha_2->setChecked(true);
        tbFuncAlpha_2->setAutoExclusive(true);
        gbBaudRate_2 = new QGroupBox(gbCustomers);
        gbBaudRate_2->setObjectName(QString::fromUtf8("gbBaudRate_2"));
        gbBaudRate_2->setGeometry(QRect(402, 18, 137, 45));
        tb512_2 = new QToolButton(gbBaudRate_2);
        tb512_2->setObjectName(QString::fromUtf8("tb512_2"));
        tb512_2->setGeometry(QRect(4, 14, 42, 26));
        tb512_2->setCheckable(true);
        tb512_2->setAutoExclusive(true);
        tb2400_2 = new QToolButton(gbBaudRate_2);
        tb2400_2->setObjectName(QString::fromUtf8("tb2400_2"));
        tb2400_2->setGeometry(QRect(92, 14, 42, 26));
        tb2400_2->setCheckable(true);
        tb2400_2->setAutoExclusive(true);
        tb1200_2 = new QToolButton(gbBaudRate_2);
        tb1200_2->setObjectName(QString::fromUtf8("tb1200_2"));
        tb1200_2->setGeometry(QRect(48, 14, 42, 26));
        tb1200_2->setCheckable(true);
        tb1200_2->setChecked(true);
        tb1200_2->setAutoExclusive(true);
        label_11 = new QLabel(gbCustomers);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(210, 80, 107, 16));
        leName_2 = new QLineEdit(gbCustomers);
        leName_2->setObjectName(QString::fromUtf8("leName_2"));
        leName_2->setGeometry(QRect(316, 74, 131, 24));
        leName_2->setMaxLength(20);
        pbUpdateEntry = new QPushButton(gbCustomers);
        pbUpdateEntry->setObjectName(QString::fromUtf8("pbUpdateEntry"));
        pbUpdateEntry->setEnabled(false);
        pbUpdateEntry->setGeometry(QRect(422, 104, 100, 25));
        pbDeleteEntry = new QPushButton(gbCustomers);
        pbDeleteEntry->setObjectName(QString::fromUtf8("pbDeleteEntry"));
        pbDeleteEntry->setEnabled(false);
        pbDeleteEntry->setGeometry(QRect(526, 104, 100, 25));
        label_18 = new QLabel(gbCustomers);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(464, 80, 71, 16));
        leFrequency = new QLineEdit(gbCustomers);
        leFrequency->setObjectName(QString::fromUtf8("leFrequency"));
        leFrequency->setGeometry(QRect(542, 74, 85, 24));
        leFrequency->setMaxLength(9);
        pbAddEntry = new QPushButton(gbCustomers);
        pbAddEntry->setObjectName(QString::fromUtf8("pbAddEntry"));
        pbAddEntry->setEnabled(false);
        pbAddEntry->setGeometry(QRect(318, 104, 100, 25));
        sbMaxMsgLen = new QSpinBox(gbCustomers);
        sbMaxMsgLen->setObjectName(QString::fromUtf8("sbMaxMsgLen"));
        sbMaxMsgLen->setGeometry(QRect(126, 105, 55, 24));
        sbMaxMsgLen->setAccelerated(true);
        sbMaxMsgLen->setMaximum(500);
        sbMaxMsgLen->setValue(0);
        label_20 = new QLabel(gbCustomers);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(14, 110, 117, 16));
        pbClearAll = new QPushButton(gbCustomers);
        pbClearAll->setObjectName(QString::fromUtf8("pbClearAll"));
        pbClearAll->setEnabled(false);
        pbClearAll->setGeometry(QRect(214, 104, 100, 25));
        lwPagerIDs = new QListWidget(tabPagerIDs);
        lwPagerIDs->setObjectName(QString::fromUtf8("lwPagerIDs"));
        lwPagerIDs->setGeometry(QRect(2, 160, 643, 261));
        lwPagerIDs->setFont(font3);
        lwPagerIDs->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        label_19 = new QLabel(tabPagerIDs);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(4, 144, 637, 16));
        QPalette palette;
        QBrush brush(QColor(0, 0, 127, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        label_19->setPalette(palette);
        twMain->addTab(tabPagerIDs, QString());
        tabPagerMsgs = new QWidget();
        tabPagerMsgs->setObjectName(QString::fromUtf8("tabPagerMsgs"));
        tabPagerMsgs->setEnabled(true);
        gbPagerMessages = new QGroupBox(tabPagerMsgs);
        gbPagerMessages->setObjectName(QString::fromUtf8("gbPagerMessages"));
        gbPagerMessages->setGeometry(QRect(2, 2, 641, 231));
        gbAlphaNumeric_3 = new QGroupBox(gbPagerMessages);
        gbAlphaNumeric_3->setObjectName(QString::fromUtf8("gbAlphaNumeric_3"));
        gbAlphaNumeric_3->setGeometry(QRect(222, 18, 153, 45));
        tbAlpha_3 = new QToolButton(gbAlphaNumeric_3);
        tbAlpha_3->setObjectName(QString::fromUtf8("tbAlpha_3"));
        tbAlpha_3->setGeometry(QRect(4, 14, 70, 26));
        tbAlpha_3->setCheckable(true);
        tbAlpha_3->setChecked(true);
        tbAlpha_3->setAutoExclusive(true);
        tbNumeric_3 = new QToolButton(gbAlphaNumeric_3);
        tbNumeric_3->setObjectName(QString::fromUtf8("tbNumeric_3"));
        tbNumeric_3->setGeometry(QRect(76, 14, 70, 26));
        tbNumeric_3->setCheckable(true);
        tbNumeric_3->setAutoExclusive(true);
        gbFunctionBits_3 = new QGroupBox(gbPagerMessages);
        gbFunctionBits_3->setObjectName(QString::fromUtf8("gbFunctionBits_3"));
        gbFunctionBits_3->setGeometry(QRect(14, 18, 183, 45));
        gbFunctionBits_3->setCheckable(false);
        tbFuncNumeric_3 = new QToolButton(gbFunctionBits_3);
        tbFuncNumeric_3->setObjectName(QString::fromUtf8("tbFuncNumeric_3"));
        tbFuncNumeric_3->setGeometry(QRect(4, 14, 42, 26));
        tbFuncNumeric_3->setFont(font1);
        tbFuncNumeric_3->setIconSize(QSize(23, 23));
        tbFuncNumeric_3->setCheckable(true);
        tbFuncNumeric_3->setChecked(false);
        tbFuncNumeric_3->setAutoExclusive(true);
        tbFuncTone1_3 = new QToolButton(gbFunctionBits_3);
        tbFuncTone1_3->setObjectName(QString::fromUtf8("tbFuncTone1_3"));
        tbFuncTone1_3->setGeometry(QRect(48, 14, 42, 26));
        tbFuncTone1_3->setFont(font1);
        tbFuncTone1_3->setCheckable(true);
        tbFuncTone1_3->setChecked(false);
        tbFuncTone1_3->setAutoExclusive(true);
        tbFuncTone2_3 = new QToolButton(gbFunctionBits_3);
        tbFuncTone2_3->setObjectName(QString::fromUtf8("tbFuncTone2_3"));
        tbFuncTone2_3->setGeometry(QRect(92, 14, 42, 26));
        tbFuncTone2_3->setFont(font1);
        tbFuncTone2_3->setCheckable(true);
        tbFuncTone2_3->setChecked(false);
        tbFuncTone2_3->setAutoExclusive(true);
        tbFuncAlpha_3 = new QToolButton(gbFunctionBits_3);
        tbFuncAlpha_3->setObjectName(QString::fromUtf8("tbFuncAlpha_3"));
        tbFuncAlpha_3->setGeometry(QRect(136, 14, 42, 26));
        tbFuncAlpha_3->setFont(font1);
        tbFuncAlpha_3->setCheckable(true);
        tbFuncAlpha_3->setChecked(true);
        tbFuncAlpha_3->setAutoExclusive(true);
        teMessage_3 = new QTextEdit(gbPagerMessages);
        teMessage_3->setObjectName(QString::fromUtf8("teMessage_3"));
        teMessage_3->setGeometry(QRect(126, 144, 503, 51));
        teMessage_3->setTabChangesFocus(true);
        label_15 = new QLabel(gbPagerMessages);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(14, 122, 93, 16));
        label_16 = new QLabel(gbPagerMessages);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(14, 144, 69, 16));
        gbBaudRate_3 = new QGroupBox(gbPagerMessages);
        gbBaudRate_3->setObjectName(QString::fromUtf8("gbBaudRate_3"));
        gbBaudRate_3->setGeometry(QRect(402, 18, 137, 45));
        tb512_3 = new QToolButton(gbBaudRate_3);
        tb512_3->setObjectName(QString::fromUtf8("tb512_3"));
        tb512_3->setGeometry(QRect(4, 14, 42, 26));
        tb512_3->setCheckable(true);
        tb512_3->setAutoExclusive(true);
        tb2400_3 = new QToolButton(gbBaudRate_3);
        tb2400_3->setObjectName(QString::fromUtf8("tb2400_3"));
        tb2400_3->setGeometry(QRect(92, 14, 42, 26));
        tb2400_3->setCheckable(true);
        tb2400_3->setAutoExclusive(true);
        tb1200_3 = new QToolButton(gbBaudRate_3);
        tb1200_3->setObjectName(QString::fromUtf8("tb1200_3"));
        tb1200_3->setGeometry(QRect(48, 14, 42, 26));
        tb1200_3->setCheckable(true);
        tb1200_3->setChecked(true);
        tb1200_3->setAutoExclusive(true);
        groupBox_8 = new QGroupBox(gbPagerMessages);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(566, 18, 61, 45));
        sbTx_3 = new QSpinBox(groupBox_8);
        sbTx_3->setObjectName(QString::fromUtf8("sbTx_3"));
        sbTx_3->setGeometry(QRect(8, 16, 47, 24));
        sbTx_3->setMinimum(1);
        sbTx_3->setMaximum(8);
        leRic_3 = new QLineEdit(gbPagerMessages);
        leRic_3->setObjectName(QString::fromUtf8("leRic_3"));
        leRic_3->setGeometry(QRect(126, 118, 93, 24));
        leRic_3->setMaxLength(7);
        groupBox_9 = new QGroupBox(gbPagerMessages);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(14, 66, 183, 45));
        dtSendTime_3 = new QDateTimeEdit(groupBox_9);
        dtSendTime_3->setObjectName(QString::fromUtf8("dtSendTime_3"));
        dtSendTime_3->setGeometry(QRect(12, 16, 159, 24));
        dtSendTime_3->setWrapping(true);
        dtSendTime_3->setReadOnly(true);
        groupBox_11 = new QGroupBox(gbPagerMessages);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(464, 64, 163, 47));
        cbFlags_3 = new QComboBox(groupBox_11);
        cbFlags_3->addItem(QString());
        cbFlags_3->addItem(QString());
        cbFlags_3->addItem(QString());
        cbFlags_3->addItem(QString());
        cbFlags_3->addItem(QString());
        cbFlags_3->addItem(QString());
        cbFlags_3->addItem(QString());
        cbFlags_3->addItem(QString());
        cbFlags_3->addItem(QString());
        cbFlags_3->addItem(QString());
        cbFlags_3->setObjectName(QString::fromUtf8("cbFlags_3"));
        cbFlags_3->setGeometry(QRect(14, 16, 135, 24));
        pbDeleteEntry_3 = new QPushButton(gbPagerMessages);
        pbDeleteEntry_3->setObjectName(QString::fromUtf8("pbDeleteEntry_3"));
        pbDeleteEntry_3->setGeometry(QRect(522, 200, 105, 25));
        groupBox_10 = new QGroupBox(gbPagerMessages);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(208, 66, 245, 45));
        sbPeriodQty_3 = new QSpinBox(groupBox_10);
        sbPeriodQty_3->setObjectName(QString::fromUtf8("sbPeriodQty_3"));
        sbPeriodQty_3->setGeometry(QRect(8, 16, 47, 24));
        sbPeriodQty_3->setMaximum(60);
        cbPeriod_3 = new QComboBox(groupBox_10);
        cbPeriod_3->addItem(QString());
        cbPeriod_3->addItem(QString());
        cbPeriod_3->addItem(QString());
        cbPeriod_3->addItem(QString());
        cbPeriod_3->addItem(QString());
        cbPeriod_3->addItem(QString());
        cbPeriod_3->setObjectName(QString::fromUtf8("cbPeriod_3"));
        cbPeriod_3->setGeometry(QRect(60, 16, 83, 24));
        sbHowMany_3 = new QSpinBox(groupBox_10);
        sbHowMany_3->setObjectName(QString::fromUtf8("sbHowMany_3"));
        sbHowMany_3->setGeometry(QRect(148, 16, 87, 24));
        sbHowMany_3->setMinimum(-1);
        sbHowMany_3->setValue(-1);
        lwPages = new QListWidget(tabPagerMsgs);
        lwPages->setObjectName(QString::fromUtf8("lwPages"));
        lwPages->setGeometry(QRect(2, 248, 643, 173));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Monospace"));
        font5.setPointSize(8);
        lwPages->setFont(font5);
        lwPages->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        lwPages->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        pagerMsgsHeader = new QLabel(tabPagerMsgs);
        pagerMsgsHeader->setObjectName(QString::fromUtf8("pagerMsgsHeader"));
        pagerMsgsHeader->setGeometry(QRect(8, 234, 635, 16));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        pagerMsgsHeader->setPalette(palette1);
        twMain->addTab(tabPagerMsgs, QString());
        tabSetup = new QWidget();
        tabSetup->setObjectName(QString::fromUtf8("tabSetup"));
        pbApply = new QPushButton(tabSetup);
        pbApply->setObjectName(QString::fromUtf8("pbApply"));
        pbApply->setGeometry(QRect(554, 392, 83, 25));
        groupBox_6 = new QGroupBox(tabSetup);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(4, 2, 637, 93));
        label_22 = new QLabel(groupBox_6);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(8, 18, 617, 47));
        label_22->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_22->setWordWrap(true);
        leBaudOrder = new QLineEdit(groupBox_6);
        leBaudOrder->setObjectName(QString::fromUtf8("leBaudOrder"));
        leBaudOrder->setGeometry(QRect(204, 64, 227, 24));
        leBaudOrder->setMaxLength(29);
        groupBox_7 = new QGroupBox(tabSetup);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(4, 98, 637, 75));
        leTxOrder = new QLineEdit(groupBox_7);
        leTxOrder->setObjectName(QString::fromUtf8("leTxOrder"));
        leTxOrder->setGeometry(QRect(246, 44, 143, 24));
        label_21 = new QLabel(groupBox_7);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(6, 14, 629, 39));
        label_21->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_21->setWordWrap(true);
        groupBox_12 = new QGroupBox(tabSetup);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(4, 176, 635, 61));
        leNormInv = new QLineEdit(groupBox_12);
        leNormInv->setObjectName(QString::fromUtf8("leNormInv"));
        leNormInv->setGeometry(QRect(196, 32, 121, 24));
        leNormInv->setMaxLength(15);
        label_14 = new QLabel(groupBox_12);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(8, 16, 623, 16));
        label_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_14->setWordWrap(true);
        pbKeyTx = new QPushButton(groupBox_12);
        pbKeyTx->setObjectName(QString::fromUtf8("pbKeyTx"));
        pbKeyTx->setGeometry(QRect(320, 32, 123, 24));
        pbKeyTx->setCheckable(true);
        sbTxTest = new QSpinBox(groupBox_12);
        sbTxTest->setObjectName(QString::fromUtf8("sbTxTest"));
        sbTxTest->setGeometry(QRect(444, 32, 39, 24));
        sbTxTest->setMinimum(1);
        sbTxTest->setMaximum(8);
        groupBox_13 = new QGroupBox(tabSetup);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(4, 238, 635, 59));
        leKeyDelay = new QLineEdit(groupBox_13);
        leKeyDelay->setObjectName(QString::fromUtf8("leKeyDelay"));
        leKeyDelay->setGeometry(QRect(192, 30, 245, 24));
        label_17 = new QLabel(groupBox_13);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(6, 14, 625, 16));
        label_17->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_17->setWordWrap(true);
        groupBox_14 = new QGroupBox(tabSetup);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(4, 300, 349, 75));
        leSyncCW = new QLineEdit(groupBox_14);
        leSyncCW->setObjectName(QString::fromUtf8("leSyncCW"));
        leSyncCW->setGeometry(QRect(90, 16, 103, 24));
        leSyncCW->setMaxLength(10);
        leIdleCW = new QLineEdit(groupBox_14);
        leIdleCW->setObjectName(QString::fromUtf8("leIdleCW"));
        leIdleCW->setGeometry(QRect(90, 42, 103, 24));
        leIdleCW->setMaxLength(10);
        label_2 = new QLabel(groupBox_14);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(8, 24, 73, 16));
        label_5 = new QLabel(groupBox_14);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(8, 48, 63, 16));
        label_6 = new QLabel(groupBox_14);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(200, 22, 133, 16));
        label_7 = new QLabel(groupBox_14);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(200, 48, 137, 16));
        groupBox_15 = new QGroupBox(tabSetup);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(358, 300, 281, 75));
        rbPic = new QRadioButton(groupBox_15);
        rbPic->setObjectName(QString::fromUtf8("rbPic"));
        rbPic->setGeometry(QRect(6, 16, 245, 20));
        rbPic->setChecked(true);
        rbSop = new QRadioButton(groupBox_15);
        rbSop->setObjectName(QString::fromUtf8("rbSop"));
        rbSop->setGeometry(QRect(6, 34, 261, 20));
        groupBox_16 = new QGroupBox(tabSetup);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(8, 380, 427, 63));
        mixer_device = new QComboBox(groupBox_16);
        mixer_device->setObjectName(QString::fromUtf8("mixer_device"));
        mixer_device->setGeometry(QRect(14, 28, 391, 25));
        twMain->addTab(tabSetup, QString());

        gridLayout->addWidget(twMain, 0, 1, 1, 1);

        MainWin->setCentralWidget(centralwidget);
        QWidget::setTabOrder(tbGetPagerID, leRic);
        QWidget::setTabOrder(leRic, teMessage);
        QWidget::setTabOrder(teMessage, lwPrevPages);
        QWidget::setTabOrder(lwPrevPages, pbSend);
        QWidget::setTabOrder(pbSend, tbFuncNumeric);
        QWidget::setTabOrder(tbFuncNumeric, tbFuncTone1);
        QWidget::setTabOrder(tbFuncTone1, tbFuncTone2);
        QWidget::setTabOrder(tbFuncTone2, tbFuncAlpha);
        QWidget::setTabOrder(tbFuncAlpha, tbAlpha);
        QWidget::setTabOrder(tbAlpha, tbNumeric);
        QWidget::setTabOrder(tbNumeric, tb512);
        QWidget::setTabOrder(tb512, tb1200);
        QWidget::setTabOrder(tb1200, tb2400);
        QWidget::setTabOrder(tb2400, tbNormal);
        QWidget::setTabOrder(tbNormal, tbInverted);
        QWidget::setTabOrder(tbInverted, dtSendTime);
        QWidget::setTabOrder(dtSendTime, sbPeriodQty);
        QWidget::setTabOrder(sbPeriodQty, cbPeriod);
        QWidget::setTabOrder(cbPeriod, sbTx);
        QWidget::setTabOrder(sbTx, lePagerName);
        QWidget::setTabOrder(lePagerName, tbTune);
        QWidget::setTabOrder(tbTune, pocsagLevel);
        QWidget::setTabOrder(pocsagLevel, lwRicSearch);
        QWidget::setTabOrder(lwRicSearch, leStartRic);
        QWidget::setTabOrder(leStartRic, sbAmtRics);
        QWidget::setTabOrder(sbAmtRics, sbAmtTxs);
        QWidget::setTabOrder(sbAmtTxs, cbSendRic);
        QWidget::setTabOrder(cbSendRic, pbStart);
        QWidget::setTabOrder(pbStart, pbAbort);
        QWidget::setTabOrder(pbAbort, lwPocsag);
        QWidget::setTabOrder(lwPocsag, logFile);
        QWidget::setTabOrder(logFile, pbReload);
        QWidget::setTabOrder(pbReload, pbSave);
        QWidget::setTabOrder(pbSave, leBaudOrder);

        retranslateUi(MainWin);

        twMain->setCurrentIndex(6);


        QMetaObject::connectSlotsByName(MainWin);
    } // setupUi

    void retranslateUi(QMainWindow *MainWin)
    {
        MainWin->setWindowTitle(QCoreApplication::translate("MainWin", "GasCop Paging Encoder", nullptr));
        action_Help->setText(QCoreApplication::translate("MainWin", "&Help", nullptr));
        action_About->setText(QCoreApplication::translate("MainWin", "&About", nullptr));
        mnDisplayPocsag->setText(QCoreApplication::translate("MainWin", "&Display Pocsag Data", nullptr));
        mnSendSinglePage->setText(QCoreApplication::translate("MainWin", "Send &Single Page", nullptr));
        teMessage->setHtml(QCoreApplication::translate("MainWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Noto Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Sans Serif'; font-size:9pt;\"><br /></p></body></html>", nullptr));
        label->setText(QCoreApplication::translate("MainWin", "RIC/CAP Code", nullptr));
        label_4->setText(QCoreApplication::translate("MainWin", "Message", nullptr));
        pbSend->setText(QCoreApplication::translate("MainWin", "&Send", nullptr));
        gbFunctionBits->setTitle(QCoreApplication::translate("MainWin", "Function Bits", nullptr));
        tbFuncNumeric->setText(QCoreApplication::translate("MainWin", "Num", nullptr));
        tbFuncTone1->setText(QCoreApplication::translate("MainWin", "T1", nullptr));
        tbFuncTone2->setText(QCoreApplication::translate("MainWin", "T2", nullptr));
        tbFuncAlpha->setText(QCoreApplication::translate("MainWin", "Alpha", nullptr));
        gbBaudRate->setTitle(QCoreApplication::translate("MainWin", "Baud Rate", nullptr));
        tb512->setText(QCoreApplication::translate("MainWin", "512", nullptr));
        tb2400->setText(QCoreApplication::translate("MainWin", "2400", nullptr));
        tb1200->setText(QCoreApplication::translate("MainWin", "1200", nullptr));
        gbAlphaNumeric->setTitle(QCoreApplication::translate("MainWin", "Alpha/Numeric", nullptr));
        tbAlpha->setText(QCoreApplication::translate("MainWin", "Alpha", nullptr));
        tbNumeric->setText(QCoreApplication::translate("MainWin", "Numeric", nullptr));
        gbDataState->setTitle(QCoreApplication::translate("MainWin", "Data Polarity", nullptr));
        tbNormal->setText(QCoreApplication::translate("MainWin", "Normal", nullptr));
        tbInverted->setText(QCoreApplication::translate("MainWin", "Inverted", nullptr));
        gbTuneup->setTitle(QCoreApplication::translate("MainWin", "Tuneup", nullptr));
        tbTune->setText(QCoreApplication::translate("MainWin", "Tune up", nullptr));
        tbTuneStop->setText(QCoreApplication::translate("MainWin", "Stop Tune up", nullptr));
        gbLevel->setTitle(QCoreApplication::translate("MainWin", "Set Data Level", nullptr));
        label_3->setText(QCoreApplication::translate("MainWin", "1     2     3     4     5     6     7     8     9", nullptr));
        levelLabel->setText(QCoreApplication::translate("MainWin", "100", nullptr));
        label_9->setText(QCoreApplication::translate("MainWin", "Previous Msgs", nullptr));
        verLabel->setText(QCoreApplication::translate("MainWin", "Version", nullptr));
        groupBox->setTitle(QCoreApplication::translate("MainWin", "Repeat Page Every", nullptr));
        cbPeriod->setItemText(0, QCoreApplication::translate("MainWin", "Minutes", nullptr));
        cbPeriod->setItemText(1, QCoreApplication::translate("MainWin", "Hours", nullptr));
        cbPeriod->setItemText(2, QCoreApplication::translate("MainWin", "Days", nullptr));
        cbPeriod->setItemText(3, QCoreApplication::translate("MainWin", "Weeks", nullptr));
        cbPeriod->setItemText(4, QCoreApplication::translate("MainWin", "Months", nullptr));
        cbPeriod->setItemText(5, QCoreApplication::translate("MainWin", "Years", nullptr));

        sbHowMany->setSuffix(QCoreApplication::translate("MainWin", " Times", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("MainWin", "Send Time", nullptr));
        dtSendTime->setDisplayFormat(QCoreApplication::translate("MainWin", "dd/MM/yyyy HH:mm:ss", nullptr));
        tbResetTime->setText(QString());
        groupBox_3->setTitle(QCoreApplication::translate("MainWin", "Tx", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("MainWin", "Pager ID Name", nullptr));
        tbGetPagerID->setText(QCoreApplication::translate("MainWin", "...", nullptr));
        twMain->setTabText(twMain->indexOf(tabPageEnter), QCoreApplication::translate("MainWin", "Page Entry", nullptr));
        leStartRic->setInputMask(QCoreApplication::translate("MainWin", "9999999", nullptr));
        leStartRic->setText(QCoreApplication::translate("MainWin", "1000000", nullptr));
        label_10->setText(QCoreApplication::translate("MainWin", "Start RIC", nullptr));
        searchInfo->setText(QString());
        pbStart->setText(QCoreApplication::translate("MainWin", "&Start", nullptr));
        label_12->setText(QCoreApplication::translate("MainWin", "The function bits, baud rate and data polarity settings from the 'Page Entry' tab will be used here. The start RIC auto updates to the next value after each transmission.", nullptr));
        sbAmtRics->setSuffix(QCoreApplication::translate("MainWin", " RICs per transmission", nullptr));
        sbAmtRics->setPrefix(QCoreApplication::translate("MainWin", "Send ", nullptr));
        sbAmtTxs->setSuffix(QCoreApplication::translate("MainWin", " transmissions", nullptr));
        sbAmtTxs->setPrefix(QCoreApplication::translate("MainWin", "Make ", nullptr));
        cbSendRic->setText(QCoreApplication::translate("MainWin", "Send RIC to pager", nullptr));
        pbAbort->setText(QCoreApplication::translate("MainWin", "&Abort", nullptr));
        twMain->setTabText(twMain->indexOf(tabRicSearch), QCoreApplication::translate("MainWin", "RIC Search", nullptr));
        twMain->setTabText(twMain->indexOf(tabPocsagData), QCoreApplication::translate("MainWin", "Pocsag Data", nullptr));
        pbSave->setText(QCoreApplication::translate("MainWin", "&Save", nullptr));
        pbReload->setText(QCoreApplication::translate("MainWin", "&Reload", nullptr));
        twMain->setTabText(twMain->indexOf(tabLogFile), QCoreApplication::translate("MainWin", "Log File", nullptr));
        gbCustomers->setTitle(QCoreApplication::translate("MainWin", "Pager IDs", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("MainWin", "Tx", nullptr));
        leRic_2->setText(QString());
        gbAlphaNumeric_2->setTitle(QCoreApplication::translate("MainWin", "Alpha/Numeric", nullptr));
        tbAlpha_2->setText(QCoreApplication::translate("MainWin", "Alpha", nullptr));
        tbNumeric_2->setText(QCoreApplication::translate("MainWin", "Numeric", nullptr));
        label_13->setText(QCoreApplication::translate("MainWin", "RIC/CAP Code", nullptr));
        gbFunctionBits_2->setTitle(QCoreApplication::translate("MainWin", "Function Bits", nullptr));
        tbFuncNumeric_2->setText(QCoreApplication::translate("MainWin", "Num", nullptr));
        tbFuncTone1_2->setText(QCoreApplication::translate("MainWin", "T1", nullptr));
        tbFuncTone2_2->setText(QCoreApplication::translate("MainWin", "T2", nullptr));
        tbFuncAlpha_2->setText(QCoreApplication::translate("MainWin", "Alpha", nullptr));
        gbBaudRate_2->setTitle(QCoreApplication::translate("MainWin", "Baud Rate", nullptr));
        tb512_2->setText(QCoreApplication::translate("MainWin", "512", nullptr));
        tb2400_2->setText(QCoreApplication::translate("MainWin", "2400", nullptr));
        tb1200_2->setText(QCoreApplication::translate("MainWin", "1200", nullptr));
        label_11->setText(QCoreApplication::translate("MainWin", "Pager ID Name", nullptr));
        pbUpdateEntry->setText(QCoreApplication::translate("MainWin", "&Update Entry", nullptr));
        pbDeleteEntry->setText(QCoreApplication::translate("MainWin", "&Delete Entry", nullptr));
        label_18->setText(QCoreApplication::translate("MainWin", "Frequency", nullptr));
        leFrequency->setText(QString());
        pbAddEntry->setText(QCoreApplication::translate("MainWin", "&Add Entry", nullptr));
        label_20->setText(QCoreApplication::translate("MainWin", "Max Msg Length", nullptr));
        pbClearAll->setText(QCoreApplication::translate("MainWin", "&Clear All", nullptr));
        label_19->setText(QCoreApplication::translate("MainWin", "Pager ID name                      RIC             Baud   T     Frequency     F     A/N           Msg Len", nullptr));
        twMain->setTabText(twMain->indexOf(tabPagerIDs), QCoreApplication::translate("MainWin", "Pager IDs", nullptr));
        gbPagerMessages->setTitle(QCoreApplication::translate("MainWin", "Pager Messages", nullptr));
        gbAlphaNumeric_3->setTitle(QCoreApplication::translate("MainWin", "Alpha/Numeric", nullptr));
        tbAlpha_3->setText(QCoreApplication::translate("MainWin", "Alpha", nullptr));
        tbNumeric_3->setText(QCoreApplication::translate("MainWin", "Numeric", nullptr));
        gbFunctionBits_3->setTitle(QCoreApplication::translate("MainWin", "Function Bits", nullptr));
        tbFuncNumeric_3->setText(QCoreApplication::translate("MainWin", "Num", nullptr));
        tbFuncTone1_3->setText(QCoreApplication::translate("MainWin", "T1", nullptr));
        tbFuncTone2_3->setText(QCoreApplication::translate("MainWin", "T2", nullptr));
        tbFuncAlpha_3->setText(QCoreApplication::translate("MainWin", "Alpha", nullptr));
        teMessage_3->setHtml(QCoreApplication::translate("MainWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Noto Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Sans Serif'; font-size:9pt;\"><br /></p></body></html>", nullptr));
        label_15->setText(QCoreApplication::translate("MainWin", "RIC/CAP Code", nullptr));
        label_16->setText(QCoreApplication::translate("MainWin", "Message", nullptr));
        gbBaudRate_3->setTitle(QCoreApplication::translate("MainWin", "Baud Rate", nullptr));
        tb512_3->setText(QCoreApplication::translate("MainWin", "512", nullptr));
        tb2400_3->setText(QCoreApplication::translate("MainWin", "2400", nullptr));
        tb1200_3->setText(QCoreApplication::translate("MainWin", "1200", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("MainWin", "Tx", nullptr));
        groupBox_9->setTitle(QCoreApplication::translate("MainWin", "Send Time", nullptr));
        dtSendTime_3->setDisplayFormat(QCoreApplication::translate("MainWin", "dd/MM/yyyy HH:mm:ss", nullptr));
        groupBox_11->setTitle(QCoreApplication::translate("MainWin", "Flags", nullptr));
        cbFlags_3->setItemText(0, QCoreApplication::translate("MainWin", "Waiting", nullptr));
        cbFlags_3->setItemText(1, QCoreApplication::translate("MainWin", "Sending", nullptr));
        cbFlags_3->setItemText(2, QCoreApplication::translate("MainWin", "Not Used", nullptr));
        cbFlags_3->setItemText(3, QCoreApplication::translate("MainWin", "Not Used", nullptr));
        cbFlags_3->setItemText(4, QCoreApplication::translate("MainWin", "Not Used", nullptr));
        cbFlags_3->setItemText(5, QCoreApplication::translate("MainWin", "Not Used", nullptr));
        cbFlags_3->setItemText(6, QCoreApplication::translate("MainWin", "Not Used", nullptr));
        cbFlags_3->setItemText(7, QCoreApplication::translate("MainWin", "Not Used", nullptr));
        cbFlags_3->setItemText(8, QCoreApplication::translate("MainWin", "Not Used", nullptr));
        cbFlags_3->setItemText(9, QCoreApplication::translate("MainWin", "Not Used", nullptr));

        pbDeleteEntry_3->setText(QCoreApplication::translate("MainWin", "Delete &Entry", nullptr));
        groupBox_10->setTitle(QCoreApplication::translate("MainWin", "Repeat Page Every", nullptr));
        cbPeriod_3->setItemText(0, QCoreApplication::translate("MainWin", "Minutes", nullptr));
        cbPeriod_3->setItemText(1, QCoreApplication::translate("MainWin", "Hours", nullptr));
        cbPeriod_3->setItemText(2, QCoreApplication::translate("MainWin", "Days", nullptr));
        cbPeriod_3->setItemText(3, QCoreApplication::translate("MainWin", "Weeks", nullptr));
        cbPeriod_3->setItemText(4, QCoreApplication::translate("MainWin", "Months", nullptr));
        cbPeriod_3->setItemText(5, QCoreApplication::translate("MainWin", "Years", nullptr));

        sbHowMany_3->setSuffix(QCoreApplication::translate("MainWin", " Times", nullptr));
        pagerMsgsHeader->setText(QCoreApplication::translate("MainWin", "F    Send Time    RIC          Baud  T    R      Q     F     A/N         Message", nullptr));
        twMain->setTabText(twMain->indexOf(tabPagerMsgs), QCoreApplication::translate("MainWin", "Pager Msgs", nullptr));
        pbApply->setText(QCoreApplication::translate("MainWin", "&Apply", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("MainWin", "Baud Search Order", nullptr));
        label_22->setText(QCoreApplication::translate("MainWin", "Gascop can send 512, 1200 and 2400 baud. If you only use one baud rate then set all 6 entries to that baud rate. You can set something like 1200,1200,1200,512,1200,2400 to search for messages for all 3 baud rates but with a preference for 1200 baud.", nullptr));
        leBaudOrder->setInputMask(QCoreApplication::translate("MainWin", "9999,9999,9999,9999,9999,9999", nullptr));
        leBaudOrder->setText(QCoreApplication::translate("MainWin", ",,,,,", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("MainWin", "Tx Search Order", nullptr));
        leTxOrder->setInputMask(QCoreApplication::translate("MainWin", "9,9,9,9,9,9,9,9", nullptr));
        leTxOrder->setText(QCoreApplication::translate("MainWin", ",,,,,,,", nullptr));
        label_21->setText(QCoreApplication::translate("MainWin", "Enter list of transmitters to use. Set them all to one if you only have one transmitter or for 2 transmitters set 1,2,1,2,1,2,1,2 to use them equally or 1,1,1,2,1,1,1,2 to favour transmitter 1.", nullptr));
        groupBox_12->setTitle(QCoreApplication::translate("MainWin", "Keying State", nullptr));
        leNormInv->setInputMask(QCoreApplication::translate("MainWin", "9,9,9,9,9,9,9,9", nullptr));
        leNormInv->setText(QCoreApplication::translate("MainWin", ",,,,,,,", nullptr));
        label_14->setText(QCoreApplication::translate("MainWin", "8 Channels: Enter 1 to ground the pin to key or 0 will open circuit the pin to key.", nullptr));
        pbKeyTx->setText(QCoreApplication::translate("MainWin", "Key Transmitter", nullptr));
        groupBox_13->setTitle(QCoreApplication::translate("MainWin", "Delay After Keying", nullptr));
        leKeyDelay->setInputMask(QCoreApplication::translate("MainWin", "999,999,999,999,999,999,999,999", nullptr));
        leKeyDelay->setText(QCoreApplication::translate("MainWin", ",,,,,,,", nullptr));
        label_17->setText(QCoreApplication::translate("MainWin", "8 Channels: Enter 8 values from 0 to 999ms for a delay between keying and sending.", nullptr));
        groupBox_14->setTitle(QCoreApplication::translate("MainWin", "Sync & Idle", nullptr));
        leSyncCW->setInputMask(QCoreApplication::translate("MainWin", "\\0\\xHHHHHHHH", nullptr));
        leSyncCW->setText(QCoreApplication::translate("MainWin", "0x", nullptr));
        leIdleCW->setInputMask(QCoreApplication::translate("MainWin", "\\0\\xHHHHHHHH", nullptr));
        leIdleCW->setText(QCoreApplication::translate("MainWin", "0x", nullptr));
        label_2->setText(QCoreApplication::translate("MainWin", "Sync CW", nullptr));
        label_5->setText(QCoreApplication::translate("MainWin", "Idle CW", nullptr));
        label_6->setText(QCoreApplication::translate("MainWin", "Default: 0x7cd215d8", nullptr));
        label_7->setText(QCoreApplication::translate("MainWin", "Default: 0x7a89c197", nullptr));
        groupBox_15->setTitle(QCoreApplication::translate("MainWin", "Interface", nullptr));
        rbPic->setText(QCoreApplication::translate("MainWin", "PIC 16C63 Interface", nullptr));
        rbSop->setText(QCoreApplication::translate("MainWin", "Slice of Pi Interface", nullptr));
        groupBox_16->setTitle(QCoreApplication::translate("MainWin", "Sound Device", nullptr));
        twMain->setTabText(twMain->indexOf(tabSetup), QCoreApplication::translate("MainWin", "Setup", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWin: public Ui_MainWin {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWIN_H
